CommitMsg:
  CapitalizedSubject:
    enabled: true

  EmptyMessage:
    enabled: false

  TrailingPeriod:
    enabled: true

  TextWidth:
    enabled: false

PreCommit:
  ALL:
    on_warn: fail

  AuthorEmail:
    enabled: false

  AuthorName:
    enabled: false

  MergeConflicts:
    enabled: true

  TrailingWhitespace:
    enabled: true

  RuboCop:
    enabled: true

  Fasterer:
    enabled: true
