sudo: false
dist: trusty

cache:
  bundler: true

language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - rbx-2
  - ruby-head

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true

before_install:
  - gem update --system
  - gem update --remote bundler

bundler_args: --jobs 1 --retry 3 --without development

# after_success:
#   - bundle exec codeclimate-test-reporter

# addons:
#   code_climate:
#     repo_token: <Get from Code Climate>
