before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
language: ruby
rvm:
  - 1.8
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - rbx
  - ruby-head
matrix:
  include:
    - rvm: jruby-18mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx
    - rvm: ruby-head
  fast_finish: true
