language: ruby
sudo: false
rvm:
  - 1.8
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.0
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
