cache: bundler

language: ruby

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

sudo: true

bundler_args: --jobs 1 --retry 3 --without development

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

env:
  global:
    - CC_TEST_REPORTER_ID=3e6be56b2a7bbe02b05521f6d8014aa13e2e0809b485e5f0a21551879a756b20
    - CF_RUN_PERM_SPECS=false
