name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['**']

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [1.9, '2.0', 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, '3.0', head]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
        continue-on-error: ${{ matrix.ruby == 'head' }}
      - uses: paambaati/codeclimate-action@v3.0.0
        if: ${{ matrix.ruby == '2.7' }} # 3.0 is failed due to the old json gem's version
        with:
          coverageLocations: '${{ github.workspace }}/coverage/coverage.json:simplecov'
        env:
          CC_TEST_REPORTER_ID: 3e6be56b2a7bbe02b05521f6d8014aa13e2e0809b485e5f0a21551879a756b20
